version = 0.1
[default.deploy.parameters]
stack_name = "dynamodb-glue-hudi-pipeline"
resolve_s3 = true
s3_prefix = "dynamodb-glue-hudi-pipeline"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
